server:
  port: 9000

spring:
  application:
    name: zuul-server


  datasource:
    url: jdbc:mysql://119.3.157.136:3306/contesthelper?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update




zuul:
  servlet-path: /
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 8000

#  routes:
#    eureka-provider:
#      path: /service1/**
#      serverId: eureka-provider


ribbon:
  ReadTimeout: 8000
  SocketTimeout: 8000
  ConnectTimeout: 8000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: 39.106.62.146:${server.port}
    ip-address: 39.106.62.146
  client:
    serviceUrl:
      defaultZone: http://root:123456@39.106.62.146:8761/eureka/