server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/contesthelper?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
    instance-id: 39.106.62.146:${server.port}
    ip-address: 39.106.62.146
  client:
    serviceUrl:
      defaultZone: http://root:123456@39.106.62.146:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
