server:
  port: 7004

spring:
  application:
    name: community-server
  datasource:
    url: jdbc:mysql://localhost:3306/contesthelper?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  instance:
    prefer-ip-address: true
    instance-id: 119.3.157.136:${server.port}
    ip-address: 119.3.157.136
  client:
    serviceUrl:
      defaultZone: http://root:123456@39.106.62.146:8761/eureka/



